// generated by audio/narrate.py — voice-over line lengths and word timings
export default {
 "hook": {
  "file": "vo/paper-fold/hook.wav",
  "dur": 3.09,
  "text": "What if you could fold a piece of paper one hundred and three times?",
  "words": [
   [
    "What",
    0.0,
    0.14
   ],
   [
    "if",
    0.14,
    0.26
   ],
   [
    "you",
    0.26,
    0.38
   ],
   [
    "could",
    0.38,
    0.56
   ],
   [
    "fold",
    0.56,
    0.78
   ],
   [
    "a",
    0.78,
    0.94
   ],
   [
    "piece",
    0.94,
    1.1
   ],
   [
    "of",
    1.1,
    1.32
   ],
   [
    "paper",
    1.32,
    1.5
   ],
   [
    "one",
    1.5,
    1.74
   ],
   [
    "hundred",
    1.74,
    2.12
   ],
   [
    "and",
    2.12,
    2.3
   ],
   [
    "three",
    2.3,
    2.52
   ],
   [
    "times?",
    2.52,
    2.88
   ]
  ]
 },
 "double": {
  "file": "vo/paper-fold/double.wav",
  "dur": 1.93,
  "text": "Every fold makes it twice as thick.",
  "words": [
   [
    "Every",
    0.0,
    0.24
   ],
   [
    "fold",
    0.24,
    0.6
   ],
   [
    "makes",
    0.6,
    0.84
   ],
   [
    "it",
    0.84,
    1.04
   ],
   [
    "twice",
    1.04,
    1.28
   ],
   [
    "as",
    1.28,
    1.52
   ],
   [
    "thick.",
    1.52,
    1.78
   ]
  ]
 },
 "c16": {
  "file": "vo/paper-fold/c16.wav",
  "dur": 0.77,
  "text": "Sixteen.",
  "words": [
   [
    "Sixteen.",
    0.0,
    0.52
   ]
  ]
 },
 "c32": {
  "file": "vo/paper-fold/c32.wav",
  "dur": 0.85,
  "text": "Thirty-two.",
  "words": [
   [
    "Thirty-two.",
    0.0,
    0.66
   ]
  ]
 },
 "c64": {
  "file": "vo/paper-fold/c64.wav",
  "dur": 0.94,
  "text": "Sixty-four.",
  "words": [
   [
    "Sixty-four.",
    0.0,
    0.42
   ]
  ]
 },
 "stuck": {
  "file": "vo/paper-fold/stuck.wav",
  "dur": 2.41,
  "text": "By hand, you'll get stuck at about seven folds.",
  "words": [
   [
    "By",
    0.0,
    0.14
   ],
   [
    "hand,",
    0.14,
    0.44
   ],
   [
    "you'll",
    0.56,
    0.64
   ],
   [
    "get",
    0.64,
    0.74
   ],
   [
    "stuck",
    0.74,
    1.02
   ],
   [
    "at",
    1.02,
    1.28
   ],
   [
    "about",
    1.28,
    1.44
   ],
   [
    "seven",
    1.44,
    1.82
   ],
   [
    "folds.",
    1.82,
    2.18
   ]
  ]
 },
 "keep": {
  "file": "vo/paper-fold/keep.wav",
  "dur": 1.6,
  "text": "But what if you could keep going?",
  "words": [
   [
    "But",
    0.0,
    0.14
   ],
   [
    "what",
    0.14,
    0.3
   ],
   [
    "if",
    0.3,
    0.46
   ],
   [
    "you",
    0.46,
    0.6
   ],
   [
    "could",
    0.6,
    0.78
   ],
   [
    "keep",
    0.78,
    1.0
   ],
   [
    "going?",
    1.0,
    1.4
   ]
  ]
 },
 "mug": {
  "file": "vo/paper-fold/mug.wav",
  "dur": 2.36,
  "text": "Ten folds, and it's as tall as a coffee mug.",
  "words": [
   [
    "Ten",
    0.0,
    0.18
   ],
   [
    "folds,",
    0.18,
    0.62
   ],
   [
    "and",
    0.8,
    0.86
   ],
   [
    "it's",
    0.86,
    1.02
   ],
   [
    "as",
    1.02,
    1.14
   ],
   [
    "tall",
    1.14,
    1.4
   ],
   [
    "as",
    1.4,
    1.6
   ],
   [
    "a",
    1.6,
    1.7
   ],
   [
    "coffee",
    1.7,
    1.98
   ],
   [
    "mug.",
    1.98,
    2.24
   ]
  ]
 },
 "you": {
  "file": "vo/paper-fold/you.wav",
  "dur": 2.19,
  "text": "Fourteen folds, and it's as tall as you.",
  "words": [
   [
    "Fourteen",
    0.0,
    0.42
   ],
   [
    "folds,",
    0.42,
    0.8
   ],
   [
    "and",
    1.08,
    1.1
   ],
   [
    "it's",
    1.1,
    1.28
   ],
   [
    "as",
    1.28,
    1.38
   ],
   [
    "tall",
    1.38,
    1.62
   ],
   [
    "as",
    1.62,
    1.82
   ],
   [
    "you.",
    1.82,
    2.04
   ]
  ]
 },
 "bldg": {
  "file": "vo/paper-fold/bldg.wav",
  "dur": 3.09,
  "text": "Seventeen folds, and it's as tall as a four-storey building.",
  "words": [
   [
    "Seventeen",
    0.0,
    0.54
   ],
   [
    "folds,",
    0.54,
    0.82
   ],
   [
    "and",
    1.1,
    1.18
   ],
   [
    "it's",
    1.18,
    1.32
   ],
   [
    "as",
    1.32,
    1.44
   ],
   [
    "tall",
    1.44,
    1.7
   ],
   [
    "as",
    1.7,
    1.94
   ],
   [
    "a",
    1.94,
    2.04
   ],
   [
    "four-storey",
    2.04,
    2.68
   ],
   [
    "building.",
    2.68,
    2.88
   ]
  ]
 },
 "tower": {
  "file": "vo/paper-fold/tower.wav",
  "dur": 2.85,
  "text": "Twenty folds, and it's taller than a thirty-storey tower.",
  "words": [
   [
    "Twenty",
    0.0,
    0.24
   ],
   [
    "folds,",
    0.24,
    0.68
   ],
   [
    "and",
    0.9,
    0.92
   ],
   [
    "it's",
    0.92,
    1.12
   ],
   [
    "taller",
    1.12,
    1.34
   ],
   [
    "than",
    1.34,
    1.6
   ],
   [
    "a",
    1.6,
    1.74
   ],
   [
    "thirty-storey",
    1.74,
    2.44
   ],
   [
    "tower.",
    2.44,
    2.62
   ]
  ]
 },
 "tallest": {
  "file": "vo/paper-fold/tallest.wav",
  "dur": 3.22,
  "text": "Twenty-three folds, and it's taller than the tallest building on Earth.",
  "words": [
   [
    "Twenty-three",
    0.0,
    0.5
   ],
   [
    "folds,",
    0.5,
    0.86
   ],
   [
    "and",
    1.14,
    1.18
   ],
   [
    "it's",
    1.18,
    1.42
   ],
   [
    "taller",
    1.42,
    1.64
   ],
   [
    "than",
    1.64,
    1.88
   ],
   [
    "the",
    1.88,
    2.0
   ],
   [
    "tallest",
    2.0,
    2.3
   ],
   [
    "building",
    2.3,
    2.68
   ],
   [
    "on",
    2.68,
    2.9
   ],
   [
    "Earth.",
    2.9,
    3.08
   ]
  ]
 },
 "planes": {
  "file": "vo/paper-fold/planes.wav",
  "dur": 2.66,
  "text": "Twenty-seven folds, and it's higher than planes fly.",
  "words": [
   [
    "Twenty-seven",
    0.0,
    0.54
   ],
   [
    "folds,",
    0.54,
    0.94
   ],
   [
    "and",
    1.22,
    1.24
   ],
   [
    "it's",
    1.24,
    1.44
   ],
   [
    "higher",
    1.44,
    1.62
   ],
   [
    "than",
    1.62,
    1.86
   ],
   [
    "planes",
    1.86,
    2.16
   ],
   [
    "fly.",
    2.16,
    2.5
   ]
  ]
 },
 "space": {
  "file": "vo/paper-fold/space.wav",
  "dur": 1.83,
  "text": "Thirty folds, and it reaches space.",
  "words": [
   [
    "Thirty",
    0.0,
    0.24
   ],
   [
    "folds,",
    0.24,
    0.66
   ],
   [
    "and",
    0.82,
    0.86
   ],
   [
    "it",
    0.86,
    0.96
   ],
   [
    "reaches",
    0.96,
    1.24
   ],
   [
    "space.",
    1.24,
    1.58
   ]
  ]
 },
 "moon": {
  "file": "vo/paper-fold/moon.wav",
  "dur": 2.34,
  "text": "Forty-two folds, and it reaches past the Moon.",
  "words": [
   [
    "Forty-two",
    0.0,
    0.48
   ],
   [
    "folds,",
    0.48,
    0.82
   ],
   [
    "and",
    1.1,
    1.1
   ],
   [
    "it",
    1.1,
    1.2
   ],
   [
    "reaches",
    1.2,
    1.44
   ],
   [
    "past",
    1.44,
    1.76
   ],
   [
    "the",
    1.76,
    1.96
   ],
   [
    "Moon.",
    1.96,
    2.14
   ]
  ]
 },
 "sun": {
  "file": "vo/paper-fold/sun.wav",
  "dur": 2.36,
  "text": "Fifty-one folds, and it reaches past the Sun.",
  "words": [
   [
    "Fifty-one",
    0.0,
    0.46
   ],
   [
    "folds,",
    0.46,
    0.84
   ],
   [
    "and",
    1.1,
    1.12
   ],
   [
    "it",
    1.12,
    1.22
   ],
   [
    "reaches",
    1.22,
    1.46
   ],
   [
    "past",
    1.46,
    1.78
   ],
   [
    "the",
    1.78,
    1.98
   ],
   [
    "Sun.",
    1.98,
    2.16
   ]
  ]
 },
 "galaxy": {
  "file": "vo/paper-fold/galaxy.wav",
  "dur": 3.05,
  "text": "Eighty-three folds, and it's as long as our galaxy is wide.",
  "words": [
   [
    "Eighty-three",
    0.0,
    0.5
   ],
   [
    "folds,",
    0.5,
    0.9
   ],
   [
    "and",
    1.12,
    1.18
   ],
   [
    "it's",
    1.18,
    1.34
   ],
   [
    "as",
    1.34,
    1.46
   ],
   [
    "long",
    1.46,
    1.64
   ],
   [
    "as",
    1.64,
    1.82
   ],
   [
    "our",
    1.82,
    1.94
   ],
   [
    "galaxy",
    1.94,
    2.28
   ],
   [
    "is",
    2.28,
    2.58
   ],
   [
    "wide.",
    2.58,
    2.86
   ]
  ]
 },
 "final1": {
  "file": "vo/paper-fold/final1.wav",
  "dur": 1.92,
  "text": "And at one hundred and three folds...",
  "words": [
   [
    "And",
    0.0,
    0.12
   ],
   [
    "at",
    0.12,
    0.24
   ],
   [
    "one",
    0.24,
    0.44
   ],
   [
    "hundred",
    0.44,
    0.82
   ],
   [
    "and",
    0.82,
    1.0
   ],
   [
    "three",
    1.0,
    1.24
   ],
   [
    "folds...",
    1.24,
    1.9
   ]
  ]
 },
 "final2": {
  "file": "vo/paper-fold/final2.wav",
  "dur": 3.11,
  "text": "it's longer than the entire observable universe is wide.",
  "words": [
   [
    "it's",
    0.0,
    0.24
   ],
   [
    "longer",
    0.24,
    0.44
   ],
   [
    "than",
    0.44,
    0.66
   ],
   [
    "the",
    0.66,
    0.8
   ],
   [
    "entire",
    0.8,
    1.26
   ],
   [
    "observable",
    1.26,
    1.78
   ],
   [
    "universe",
    1.78,
    2.34
   ],
   [
    "is",
    2.34,
    2.62
   ],
   [
    "wide.",
    2.62,
    2.94
   ]
  ]
 },
 "outro": {
  "file": "vo/paper-fold/outro.wav",
  "dur": 1.76,
  "text": "All from a single sheet of paper.",
  "words": [
   [
    "All",
    0.0,
    0.2
   ],
   [
    "from",
    0.2,
    0.4
   ],
   [
    "a",
    0.4,
    0.54
   ],
   [
    "single",
    0.54,
    0.8
   ],
   [
    "sheet",
    0.8,
    1.08
   ],
   [
    "of",
    1.08,
    1.24
   ],
   [
    "paper.",
    1.24,
    1.48
   ]
  ]
 }
};
