// generated by audio/narrate.py — voice-over line lengths and word timings
export default {
 "hook": {
  "file": "vo/paper-fold/hook.wav",
  "dur": 3.51,
  "text": "What if you could fold a piece of paper one hundred and three times?",
  "words": [
   [
    "What",
    0.0,
    0.2
   ],
   [
    "if",
    0.2,
    0.34
   ],
   [
    "you",
    0.34,
    0.5
   ],
   [
    "could",
    0.5,
    0.66
   ],
   [
    "fold",
    0.66,
    0.94
   ],
   [
    "a",
    0.94,
    1.12
   ],
   [
    "piece",
    1.12,
    1.26
   ],
   [
    "of",
    1.26,
    1.5
   ],
   [
    "paper",
    1.5,
    1.76
   ],
   [
    "one",
    1.76,
    2.02
   ],
   [
    "hundred",
    2.02,
    2.4
   ],
   [
    "and",
    2.4,
    2.64
   ],
   [
    "three",
    2.64,
    2.86
   ],
   [
    "times?",
    2.86,
    3.26
   ]
  ]
 },
 "double": {
  "file": "vo/paper-fold/double.wav",
  "dur": 2.74,
  "text": "Every time you fold it, it gets twice as thick.",
  "words": [
   [
    "Every",
    0.0,
    0.3
   ],
   [
    "time",
    0.3,
    0.56
   ],
   [
    "you",
    0.56,
    0.76
   ],
   [
    "fold",
    0.76,
    0.96
   ],
   [
    "it,",
    0.96,
    1.24
   ],
   [
    "it",
    1.42,
    1.6
   ],
   [
    "gets",
    1.6,
    1.82
   ],
   [
    "twice",
    1.82,
    2.08
   ],
   [
    "as",
    2.08,
    2.32
   ],
   [
    "thick.",
    2.32,
    2.62
   ]
  ]
 },
 "c16": {
  "file": "vo/paper-fold/c16.wav",
  "dur": 0.73,
  "text": "Sixteen.",
  "words": [
   [
    "Sixteen.",
    0.0,
    0.56
   ]
  ]
 },
 "c32": {
  "file": "vo/paper-fold/c32.wav",
  "dur": 0.68,
  "text": "Thirty-two.",
  "words": [
   [
    "Thirty",
    0.0,
    0.22
   ],
   [
    "-two.",
    0.22,
    0.54
   ]
  ]
 },
 "c64": {
  "file": "vo/paper-fold/c64.wav",
  "dur": 0.81,
  "text": "Sixty-four.",
  "words": [
   [
    "Sixty",
    0.0,
    0.38
   ],
   [
    "-four.",
    0.38,
    0.68
   ]
  ]
 },
 "stuck": {
  "file": "vo/paper-fold/stuck.wav",
  "dur": 2.89,
  "text": "By hand, you'll get stuck at about seven folds.",
  "words": [
   [
    "By",
    0.0,
    0.16
   ],
   [
    "hand,",
    0.16,
    0.58
   ],
   [
    "you'll",
    0.88,
    0.98
   ],
   [
    "get",
    0.98,
    1.06
   ],
   [
    "stuck",
    1.06,
    1.36
   ],
   [
    "at",
    1.36,
    1.66
   ],
   [
    "about",
    1.66,
    1.86
   ],
   [
    "seven",
    1.86,
    2.22
   ],
   [
    "folds.",
    2.22,
    2.62
   ]
  ]
 },
 "keep": {
  "file": "vo/paper-fold/keep.wav",
  "dur": 1.62,
  "text": "But what if you could keep going?",
  "words": [
   [
    "But",
    0.0,
    0.16
   ],
   [
    "what",
    0.16,
    0.38
   ],
   [
    "if",
    0.38,
    0.54
   ],
   [
    "you",
    0.54,
    0.68
   ],
   [
    "could",
    0.68,
    0.84
   ],
   [
    "keep",
    0.84,
    1.04
   ],
   [
    "going?",
    1.04,
    1.4
   ]
  ]
 },
 "mug": {
  "file": "vo/paper-fold/mug.wav",
  "dur": 3.25,
  "text": "Fold it ten times, and it's as tall as a coffee mug.",
  "words": [
   [
    "Fold",
    0.0,
    0.28
   ],
   [
    "it",
    0.28,
    0.42
   ],
   [
    "ten",
    0.42,
    0.6
   ],
   [
    "times,",
    0.6,
    1.18
   ],
   [
    "and",
    1.56,
    1.66
   ],
   [
    "it's",
    1.66,
    1.8
   ],
   [
    "as",
    1.8,
    1.92
   ],
   [
    "tall",
    1.92,
    2.2
   ],
   [
    "as",
    2.2,
    2.4
   ],
   [
    "a",
    2.4,
    2.5
   ],
   [
    "coffee",
    2.5,
    2.8
   ],
   [
    "mug.",
    2.8,
    3.06
   ]
  ]
 },
 "you": {
  "file": "vo/paper-fold/you.wav",
  "dur": 2.54,
  "text": "Fourteen folds, and it's as tall as you.",
  "words": [
   [
    "Fourteen",
    0.0,
    0.48
   ],
   [
    "folds,",
    0.48,
    0.9
   ],
   [
    "and",
    1.4,
    1.46
   ],
   [
    "it's",
    1.46,
    1.64
   ],
   [
    "as",
    1.64,
    1.74
   ],
   [
    "tall",
    1.74,
    1.98
   ],
   [
    "as",
    1.98,
    2.2
   ],
   [
    "you.",
    2.2,
    2.4
   ]
  ]
 },
 "bldg": {
  "file": "vo/paper-fold/bldg.wav",
  "dur": 3.81,
  "text": "Seventeen folds, and it's as tall as a four-storey building.",
  "words": [
   [
    "Seventeen",
    0.0,
    0.66
   ],
   [
    "folds,",
    0.66,
    1.0
   ],
   [
    "and",
    1.58,
    1.72
   ],
   [
    "it's",
    1.72,
    1.88
   ],
   [
    "as",
    1.88,
    2.0
   ],
   [
    "tall",
    2.0,
    2.3
   ],
   [
    "as",
    2.3,
    2.52
   ],
   [
    "a",
    2.52,
    2.68
   ],
   [
    "four",
    2.68,
    2.88
   ],
   [
    "-storey",
    2.88,
    3.34
   ],
   [
    "building.",
    3.34,
    3.56
   ]
  ]
 },
 "tower": {
  "file": "vo/paper-fold/tower.wav",
  "dur": 3.53,
  "text": "Twenty folds, and it's taller than a thirty-storey tower.",
  "words": [
   [
    "Twenty",
    0.0,
    0.34
   ],
   [
    "folds,",
    0.34,
    0.82
   ],
   [
    "and",
    1.26,
    1.38
   ],
   [
    "it's",
    1.38,
    1.58
   ],
   [
    "taller",
    1.58,
    1.84
   ],
   [
    "than",
    1.84,
    2.16
   ],
   [
    "a",
    2.16,
    2.32
   ],
   [
    "thirty",
    2.32,
    2.58
   ],
   [
    "-storey",
    2.58,
    3.06
   ],
   [
    "tower.",
    3.06,
    3.26
   ]
  ]
 },
 "tallest": {
  "file": "vo/paper-fold/tallest.wav",
  "dur": 3.97,
  "text": "Twenty-three folds, and it's taller than the tallest building on Earth.",
  "words": [
   [
    "Twenty",
    0.0,
    0.3
   ],
   [
    "-three",
    0.3,
    0.64
   ],
   [
    "folds,",
    0.64,
    1.12
   ],
   [
    "and",
    1.54,
    1.74
   ],
   [
    "it's",
    1.74,
    1.96
   ],
   [
    "taller",
    1.96,
    2.22
   ],
   [
    "than",
    2.22,
    2.5
   ],
   [
    "the",
    2.5,
    2.62
   ],
   [
    "tallest",
    2.62,
    2.94
   ],
   [
    "building",
    2.94,
    3.38
   ],
   [
    "on",
    3.38,
    3.66
   ],
   [
    "Earth.",
    3.66,
    3.88
   ]
  ]
 },
 "planes": {
  "file": "vo/paper-fold/planes.wav",
  "dur": 3.22,
  "text": "Twenty-seven folds, and it's higher than planes fly.",
  "words": [
   [
    "Twenty",
    0.0,
    0.22
   ],
   [
    "-seven",
    0.22,
    0.58
   ],
   [
    "folds,",
    0.58,
    1.1
   ],
   [
    "and",
    1.56,
    1.64
   ],
   [
    "it's",
    1.64,
    1.86
   ],
   [
    "higher",
    1.86,
    2.08
   ],
   [
    "than",
    2.08,
    2.34
   ],
   [
    "planes",
    2.34,
    2.68
   ],
   [
    "fly.",
    2.68,
    3.02
   ]
  ]
 },
 "space": {
  "file": "vo/paper-fold/space.wav",
  "dur": 2.04,
  "text": "Thirty folds, and it reaches space.",
  "words": [
   [
    "Thirty",
    0.0,
    0.24
   ],
   [
    "folds,",
    0.24,
    0.7
   ],
   [
    "and",
    1.04,
    1.06
   ],
   [
    "it",
    1.06,
    1.16
   ],
   [
    "reaches",
    1.16,
    1.42
   ],
   [
    "space.",
    1.42,
    1.78
   ]
  ]
 },
 "moon": {
  "file": "vo/paper-fold/moon.wav",
  "dur": 3.66,
  "text": "If you fold it forty-two times, it reaches past the Moon.",
  "words": [
   [
    "If",
    0.0,
    0.16
   ],
   [
    "you",
    0.16,
    0.3
   ],
   [
    "fold",
    0.3,
    0.54
   ],
   [
    "it",
    0.54,
    0.74
   ],
   [
    "forty",
    0.74,
    0.96
   ],
   [
    "-two",
    0.96,
    1.28
   ],
   [
    "times,",
    1.28,
    1.68
   ],
   [
    "it",
    2.2,
    2.38
   ],
   [
    "reaches",
    2.38,
    2.66
   ],
   [
    "past",
    2.66,
    3.04
   ],
   [
    "the",
    3.04,
    3.26
   ],
   [
    "Moon.",
    3.26,
    3.46
   ]
  ]
 },
 "sun": {
  "file": "vo/paper-fold/sun.wav",
  "dur": 2.88,
  "text": "Fifty-one folds, and it reaches past the Sun.",
  "words": [
   [
    "Fifty",
    0.0,
    0.2
   ],
   [
    "-one",
    0.2,
    0.52
   ],
   [
    "folds,",
    0.52,
    0.94
   ],
   [
    "and",
    1.48,
    1.54
   ],
   [
    "it",
    1.54,
    1.64
   ],
   [
    "reaches",
    1.64,
    1.88
   ],
   [
    "past",
    1.88,
    2.26
   ],
   [
    "the",
    2.26,
    2.48
   ],
   [
    "Sun.",
    2.48,
    2.66
   ]
  ]
 },
 "galaxy": {
  "file": "vo/paper-fold/galaxy.wav",
  "dur": 3.73,
  "text": "Eighty-three folds, and it's as long as our galaxy is wide.",
  "words": [
   [
    "Eighty",
    0.0,
    0.3
   ],
   [
    "-three",
    0.3,
    0.6
   ],
   [
    "folds,",
    0.6,
    1.12
   ],
   [
    "and",
    1.5,
    1.72
   ],
   [
    "it's",
    1.72,
    1.88
   ],
   [
    "as",
    1.88,
    2.0
   ],
   [
    "long",
    2.0,
    2.2
   ],
   [
    "as",
    2.2,
    2.36
   ],
   [
    "our",
    2.36,
    2.46
   ],
   [
    "galaxy",
    2.46,
    2.82
   ],
   [
    "is",
    2.82,
    3.2
   ],
   [
    "wide.",
    3.2,
    3.54
   ]
  ]
 },
 "final1": {
  "file": "vo/paper-fold/final1.wav",
  "dur": 2.05,
  "text": "And at one hundred and three folds...",
  "words": [
   [
    "And",
    0.0,
    0.16
   ],
   [
    "at",
    0.16,
    0.3
   ],
   [
    "one",
    0.3,
    0.54
   ],
   [
    "hundred",
    0.54,
    0.92
   ],
   [
    "and",
    0.92,
    1.14
   ],
   [
    "three",
    1.14,
    1.38
   ],
   [
    "folds...",
    1.38,
    2.02
   ]
  ]
 },
 "final2": {
  "file": "vo/paper-fold/final2.wav",
  "dur": 3.6,
  "text": "it's longer than the entire observable universe is wide.",
  "words": [
   [
    "It's",
    0.0,
    0.24
   ],
   [
    "longer",
    0.24,
    0.46
   ],
   [
    "than",
    0.46,
    0.76
   ],
   [
    "the",
    0.76,
    0.9
   ],
   [
    "entire",
    0.9,
    1.46
   ],
   [
    "observable",
    1.46,
    2.04
   ],
   [
    "universe",
    2.04,
    2.62
   ],
   [
    "is",
    2.62,
    3.04
   ],
   [
    "wide.",
    3.04,
    3.42
   ]
  ]
 },
 "outro": {
  "file": "vo/paper-fold/outro.wav",
  "dur": 1.84,
  "text": "All from a single sheet of paper.",
  "words": [
   [
    "All",
    0.0,
    0.24
   ],
   [
    "from",
    0.24,
    0.44
   ],
   [
    "a",
    0.44,
    0.58
   ],
   [
    "single",
    0.58,
    0.86
   ],
   [
    "sheet",
    0.86,
    1.16
   ],
   [
    "of",
    1.16,
    1.32
   ],
   [
    "paper.",
    1.32,
    1.58
   ]
  ]
 }
};
