// generated by audio/narrate.py — voice-over line lengths and word timings
export default {
 "hook": {
  "file": "vo/paper-fold/hook.wav",
  "dur": 3.09,
  "text": "What if you could fold a piece of paper one hundred and three times?",
  "words": [
   [
    "What",
    0.0,
    0.14
   ],
   [
    "if",
    0.14,
    0.26
   ],
   [
    "you",
    0.26,
    0.38
   ],
   [
    "could",
    0.38,
    0.56
   ],
   [
    "fold",
    0.56,
    0.78
   ],
   [
    "a",
    0.78,
    0.94
   ],
   [
    "piece",
    0.94,
    1.1
   ],
   [
    "of",
    1.1,
    1.32
   ],
   [
    "paper",
    1.32,
    1.5
   ],
   [
    "one",
    1.5,
    1.74
   ],
   [
    "hundred",
    1.74,
    2.12
   ],
   [
    "and",
    2.12,
    2.3
   ],
   [
    "three",
    2.3,
    2.52
   ],
   [
    "times?",
    2.52,
    2.88
   ]
  ]
 },
 "double": {
  "file": "vo/paper-fold/double.wav",
  "dur": 1.93,
  "text": "Every fold makes it twice as thick.",
  "words": [
   [
    "Every",
    0.0,
    0.24
   ],
   [
    "fold",
    0.24,
    0.6
   ],
   [
    "makes",
    0.6,
    0.84
   ],
   [
    "it",
    0.84,
    1.04
   ],
   [
    "twice",
    1.04,
    1.28
   ],
   [
    "as",
    1.28,
    1.52
   ],
   [
    "thick.",
    1.52,
    1.78
   ]
  ]
 },
 "c16": {
  "file": "vo/paper-fold/c16.wav",
  "dur": 0.77,
  "text": "Sixteen.",
  "words": [
   [
    "Sixteen.",
    0.0,
    0.52
   ]
  ]
 },
 "c32": {
  "file": "vo/paper-fold/c32.wav",
  "dur": 0.85,
  "text": "Thirty-two.",
  "words": [
   [
    "Thirty-two.",
    0.0,
    0.66
   ]
  ]
 },
 "c64": {
  "file": "vo/paper-fold/c64.wav",
  "dur": 0.94,
  "text": "Sixty-four.",
  "words": [
   [
    "Sixty-four.",
    0.0,
    0.42
   ]
  ]
 },
 "stuck": {
  "file": "vo/paper-fold/stuck.wav",
  "dur": 2.41,
  "text": "By hand, you'll get stuck at about seven folds.",
  "words": [
   [
    "By",
    0.0,
    0.14
   ],
   [
    "hand,",
    0.14,
    0.44
   ],
   [
    "you'll",
    0.56,
    0.64
   ],
   [
    "get",
    0.64,
    0.74
   ],
   [
    "stuck",
    0.74,
    1.02
   ],
   [
    "at",
    1.02,
    1.28
   ],
   [
    "about",
    1.28,
    1.44
   ],
   [
    "seven",
    1.44,
    1.82
   ],
   [
    "folds.",
    1.82,
    2.18
   ]
  ]
 },
 "keep": {
  "file": "vo/paper-fold/keep.wav",
  "dur": 1.6,
  "text": "But what if you could keep going?",
  "words": [
   [
    "But",
    0.0,
    0.14
   ],
   [
    "what",
    0.14,
    0.3
   ],
   [
    "if",
    0.3,
    0.46
   ],
   [
    "you",
    0.46,
    0.6
   ],
   [
    "could",
    0.6,
    0.78
   ],
   [
    "keep",
    0.78,
    1.0
   ],
   [
    "going?",
    1.0,
    1.4
   ]
  ]
 },
 "mug": {
  "file": "vo/paper-fold/mug.wav",
  "dur": 2.11,
  "text": "Ten folds, and you're up to a coffee mug.",
  "words": [
   [
    "Ten",
    0.0,
    0.2
   ],
   [
    "folds,",
    0.2,
    0.62
   ],
   [
    "and",
    0.8,
    0.86
   ],
   [
    "you're",
    0.86,
    1.0
   ],
   [
    "up",
    1.0,
    1.12
   ],
   [
    "to",
    1.12,
    1.3
   ],
   [
    "a",
    1.3,
    1.42
   ],
   [
    "coffee",
    1.42,
    1.7
   ],
   [
    "mug.",
    1.7,
    1.94
   ]
  ]
 },
 "you": {
  "file": "vo/paper-fold/you.wav",
  "dur": 2.25,
  "text": "By fourteen folds, it's as tall as you.",
  "words": [
   [
    "By",
    0.0,
    0.14
   ],
   [
    "fourteen",
    0.14,
    0.54
   ],
   [
    "folds,",
    0.54,
    1.06
   ],
   [
    "it's",
    1.18,
    1.34
   ],
   [
    "as",
    1.34,
    1.44
   ],
   [
    "tall",
    1.44,
    1.68
   ],
   [
    "as",
    1.68,
    1.9
   ],
   [
    "you.",
    1.9,
    2.1
   ]
  ]
 },
 "bldg": {
  "file": "vo/paper-fold/bldg.wav",
  "dur": 2.55,
  "text": "Seventeen folds. Now it's a four-storey building.",
  "words": [
   [
    "Seventeen",
    0.0,
    0.54
   ],
   [
    "folds.",
    0.54,
    0.84
   ],
   [
    "Now",
    1.18,
    1.3
   ],
   [
    "it's",
    1.3,
    1.52
   ],
   [
    "a",
    1.52,
    1.58
   ],
   [
    "four-storey",
    1.58,
    2.16
   ],
   [
    "building.",
    2.16,
    2.34
   ]
  ]
 },
 "tower": {
  "file": "vo/paper-fold/tower.wav",
  "dur": 3.22,
  "text": "Twenty folds, and it towers over a thirty-storey skyscraper.",
  "words": [
   [
    "Twenty",
    0.0,
    0.24
   ],
   [
    "folds,",
    0.24,
    0.68
   ],
   [
    "and",
    0.9,
    0.92
   ],
   [
    "it",
    0.92,
    1.02
   ],
   [
    "towers",
    1.02,
    1.36
   ],
   [
    "over",
    1.36,
    1.62
   ],
   [
    "a",
    1.62,
    1.78
   ],
   [
    "thirty-storey",
    1.78,
    2.52
   ],
   [
    "skyscraper.",
    2.52,
    3.04
   ]
  ]
 },
 "tallest": {
  "file": "vo/paper-fold/tallest.wav",
  "dur": 3.08,
  "text": "Three more folds, and the tallest building on Earth is history.",
  "words": [
   [
    "Three",
    0.0,
    0.18
   ],
   [
    "more",
    0.18,
    0.4
   ],
   [
    "folds,",
    0.4,
    0.84
   ],
   [
    "and",
    1.04,
    1.12
   ],
   [
    "the",
    1.12,
    1.22
   ],
   [
    "tallest",
    1.22,
    1.5
   ],
   [
    "building",
    1.5,
    1.84
   ],
   [
    "on",
    1.84,
    2.1
   ],
   [
    "Earth",
    2.1,
    2.28
   ],
   [
    "is",
    2.28,
    2.52
   ],
   [
    "history.",
    2.52,
    2.82
   ]
  ]
 },
 "planes": {
  "file": "vo/paper-fold/planes.wav",
  "dur": 2.29,
  "text": "Four more folds, and it's above the planes.",
  "words": [
   [
    "Four",
    0.0,
    0.24
   ],
   [
    "more",
    0.24,
    0.44
   ],
   [
    "folds,",
    0.44,
    0.9
   ],
   [
    "and",
    1.08,
    1.12
   ],
   [
    "it's",
    1.12,
    1.32
   ],
   [
    "above",
    1.32,
    1.5
   ],
   [
    "the",
    1.5,
    1.68
   ],
   [
    "planes.",
    1.68,
    1.98
   ]
  ]
 },
 "space": {
  "file": "vo/paper-fold/space.wav",
  "dur": 1.95,
  "text": "At thirty folds, it's touching space.",
  "words": [
   [
    "At",
    0.0,
    0.16
   ],
   [
    "thirty",
    0.16,
    0.42
   ],
   [
    "folds,",
    0.42,
    0.84
   ],
   [
    "it's",
    0.94,
    1.06
   ],
   [
    "touching",
    1.06,
    1.34
   ],
   [
    "space.",
    1.34,
    1.72
   ]
  ]
 },
 "moon": {
  "file": "vo/paper-fold/moon.wav",
  "dur": 2.84,
  "text": "Keep going, and at forty-two it flies right past the Moon.",
  "words": [
   [
    "Keep",
    0.0,
    0.2
   ],
   [
    "going,",
    0.2,
    0.54
   ],
   [
    "and",
    0.74,
    0.76
   ],
   [
    "at",
    0.76,
    0.86
   ],
   [
    "forty-two",
    0.86,
    1.3
   ],
   [
    "it",
    1.3,
    1.44
   ],
   [
    "flies",
    1.44,
    1.68
   ],
   [
    "right",
    1.68,
    2.0
   ],
   [
    "past",
    2.0,
    2.3
   ],
   [
    "the",
    2.3,
    2.48
   ],
   [
    "Moon.",
    2.48,
    2.66
   ]
  ]
 },
 "sun": {
  "file": "vo/paper-fold/sun.wav",
  "dur": 2.1,
  "text": "By fifty-one, it's blown past the Sun.",
  "words": [
   [
    "By",
    0.0,
    0.14
   ],
   [
    "fifty-one,",
    0.14,
    0.66
   ],
   [
    "it's",
    0.82,
    0.94
   ],
   [
    "blown",
    0.94,
    1.2
   ],
   [
    "past",
    1.2,
    1.52
   ],
   [
    "the",
    1.52,
    1.72
   ],
   [
    "Sun.",
    1.72,
    1.88
   ]
  ]
 },
 "galaxy": {
  "file": "vo/paper-fold/galaxy.wav",
  "dur": 3.3,
  "text": "Eighty-three folds, and it stretches across our entire galaxy.",
  "words": [
   [
    "Eighty-three",
    0.0,
    0.5
   ],
   [
    "folds,",
    0.5,
    0.9
   ],
   [
    "and",
    1.12,
    1.18
   ],
   [
    "it",
    1.18,
    1.26
   ],
   [
    "stretches",
    1.26,
    1.6
   ],
   [
    "across",
    1.6,
    1.98
   ],
   [
    "our",
    1.98,
    2.2
   ],
   [
    "entire",
    2.2,
    2.58
   ],
   [
    "galaxy.",
    2.58,
    2.94
   ]
  ]
 },
 "final1": {
  "file": "vo/paper-fold/final1.wav",
  "dur": 1.92,
  "text": "And at one hundred and three folds...",
  "words": [
   [
    "And",
    0.0,
    0.12
   ],
   [
    "at",
    0.12,
    0.24
   ],
   [
    "one",
    0.24,
    0.44
   ],
   [
    "hundred",
    0.44,
    0.82
   ],
   [
    "and",
    0.82,
    1.0
   ],
   [
    "three",
    1.0,
    1.24
   ],
   [
    "folds...",
    1.24,
    1.9
   ]
  ]
 },
 "final2": {
  "file": "vo/paper-fold/final2.wav",
  "dur": 3.11,
  "text": "it's longer than the entire observable universe is wide.",
  "words": [
   [
    "it's",
    0.0,
    0.24
   ],
   [
    "longer",
    0.24,
    0.44
   ],
   [
    "than",
    0.44,
    0.66
   ],
   [
    "the",
    0.66,
    0.8
   ],
   [
    "entire",
    0.8,
    1.26
   ],
   [
    "observable",
    1.26,
    1.78
   ],
   [
    "universe",
    1.78,
    2.34
   ],
   [
    "is",
    2.34,
    2.62
   ],
   [
    "wide.",
    2.62,
    2.94
   ]
  ]
 },
 "outro": {
  "file": "vo/paper-fold/outro.wav",
  "dur": 1.76,
  "text": "All from a single sheet of paper.",
  "words": [
   [
    "All",
    0.0,
    0.2
   ],
   [
    "from",
    0.2,
    0.4
   ],
   [
    "a",
    0.4,
    0.54
   ],
   [
    "single",
    0.54,
    0.8
   ],
   [
    "sheet",
    0.8,
    1.08
   ],
   [
    "of",
    1.08,
    1.24
   ],
   [
    "paper.",
    1.24,
    1.48
   ]
  ]
 }
};
