"""Voice-over: synthesize each narration line with Kokoro (local neural TTS), trim and level it,
then transcribe it with Whisper to get word timings for captions and for timing the animation.

usage: python3 audio/narrate.py scenarios/paper-fold.vo.json

Reads   {"id": "...", "voice": "af_heart", "speed": 0.9, "lines": {"hook": "What if ...", ...}}
Writes  assets/vo/<id>/<line>.wav   (24 kHz mono, -20 dBFS RMS)
        scenarios/<id>.vo.js        export default { line: { file, dur, words: [[text, start, end], ...] } }

Model files (not in git): assets/tts/model.onnx and assets/tts/voices.npz, from
huggingface.co/onnx-community/Kokoro-82M-v1.0-ONNX (onnx/model.onnx and voices/*.bin).
"""
import json, os, sys, re
import numpy as np
import soundfile as sf
from scipy.signal import resample_poly, butter, sosfilt

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def trim(a, sr, thr_db=-42, pad=0.03):
    """Cut leading and trailing silence, keeping a short pad."""
    w = int(sr * 0.01)
    env = np.array([np.sqrt(np.mean(a[i:i + w] ** 2) + 1e-12) for i in range(0, len(a), w)])
    on = np.where(20 * np.log10(env) > thr_db)[0]
    if not len(on):
        return a
    s = max(0, on[0] * w - int(pad * sr)); e = min(len(a), (on[-1] + 1) * w + int(pad * sr))
    out = a[s:e].copy()
    f = int(0.01 * sr); out[:f] *= np.linspace(0, 1, f); out[-f:] *= np.linspace(1, 0, f)
    return out


def level(a, target_db=-20.0):
    """Gentle low cut (rumble) and RMS to the target over voiced parts."""
    a = sosfilt(butter(2, 70, 'highpass', fs=24000, output='sos'), a)
    w = 480; frames = [a[i:i + w] for i in range(0, len(a) - w, w)]
    rms = np.array([np.sqrt(np.mean(f ** 2)) for f in frames]) if frames else np.array([np.sqrt(np.mean(a ** 2))])
    voiced = rms[rms > rms.max() * 0.1] if rms.max() > 0 else rms
    g = 10 ** (target_db / 20) / max(np.sqrt(np.mean(voiced ** 2)), 1e-6)
    return np.clip(a * g, -0.98, 0.98)


def main():
    spec = json.load(open(sys.argv[1]))
    from kokoro_onnx import Kokoro
    from faster_whisper import WhisperModel
    tts = Kokoro(os.path.join(ROOT, 'assets/tts/model.onnx'), os.path.join(ROOT, 'assets/tts/voices.npz'))
    stt = WhisperModel('small.en', device='cpu', compute_type='int8')
    vid, voice, speed = spec['id'], spec.get('voice', 'af_heart'), spec.get('speed', 0.9)
    outdir = os.path.join(ROOT, 'assets', 'vo', vid); os.makedirs(outdir, exist_ok=True)
    result = {}
    for key, line in spec['lines'].items():
        text = line if isinstance(line, str) else line['say']
        sp = speed if isinstance(line, str) else line.get('speed', speed)
        audio, sr = tts.create(text, voice=voice, speed=sp, lang='en-us')
        audio = level(trim(np.asarray(audio, dtype=np.float64), sr))
        path = os.path.join(outdir, f'{key}.wav')
        sf.write(path, audio.astype(np.float32), sr)
        a16 = resample_poly(audio, 2, 3).astype(np.float32)
        segs, _ = stt.transcribe(a16, word_timestamps=True, initial_prompt=text)
        words = [[w.word.strip(), round(w.start, 3), round(w.end, 3)] for s in segs for w in s.words]
        heard = ' '.join(w[0] for w in words)
        result[key] = {'file': f'vo/{vid}/{key}.wav', 'dur': round(len(audio) / sr, 3), 'text': text, 'words': words}
        print(f'{key:10s} {len(audio) / sr:5.2f}s  {heard}', flush=True)
    js = os.path.join(ROOT, 'scenarios', f'{vid}.vo.js')
    with open(js, 'w') as f:
        f.write('// generated by audio/narrate.py — voice-over line lengths and word timings\n')
        f.write('export default ' + json.dumps(result, indent=1) + ';\n')
    print('wrote', js)


if __name__ == '__main__':
    main()
